### ISSUE TITLE
Is there something wrong with this code?

### ISSUE THREAD

**Issue by limilyli** [jleinonen/pytmatrix#21]
The part of  "radar.py" to calculate Specific attenuation (A)  means "Ah=8.686*wavelength*Imag(Shh)",   but according to formula(4.7b) in a book named "Polarimetric Doppler Weather Radar Principles and Applications" by V.N.Bringi(which is also the conference of this code),   that should be "Ah=-8.686*wavelength*Imag(Shh)",  there is a minus sign difference.  So is this part of code wrong? 
Thanks for your help!

**Comment by jleinonen** [comment]
I don't remember exactly why it's like this, but this is probably just due to different sign conventions in the matrices.

The specific attention must always be a positive number. Is the output of the function currently positive? If so, flipping the sign of the constant would make the attenuation negative which is physically impossible.

**Comment by limilyli** [comment]
yes, the outputs of A_hh,A_vv and Adp are all positive, which is in accordance with physics, so can I understand it like that "the define of the forward scattering matrices in your code are different from that in the book I mentioned above" ?

**Comment by jleinonen** [comment]
Yes, I think it has to do with this: https://en.wikipedia.org/wiki/Forward_scattering_alignment

**Comment by limilyli** [comment]
That problem has been solved, and I really appreciate your kind help!
